export const USERS = [
  { id: 1,  name: "Robert Mitchell",         role: "Managing Partner",              email: "robert.mitchell@mitchellpi.com",         initials: "RM",  phone: "(555) 400-1001", cell: "(555) 401-1001", ext: "101", avatar: "#C9A84C" },
  { id: 2,  name: "Patricia Langford",       role: "Senior Partner",                email: "patricia.langford@mitchellpi.com",       initials: "PL",  phone: "(555) 400-1002", cell: "(555) 401-1002", ext: "102", avatar: "#4C7AC9" },
  { id: 3,  name: "David Chen",              role: "Partner",                       email: "david.chen@mitchellpi.com",               initials: "DC",  phone: "(555) 400-1003", cell: "(555) 401-1003", ext: "103", avatar: "#4CAE72" },
  { id: 4,  name: "Maria Gonzalez",          role: "Partner",                       email: "maria.gonzalez@mitchellpi.com",           initials: "MG",  phone: "(555) 400-1004", cell: "(555) 401-1004", ext: "104", avatar: "#C94C4C" },
  { id: 5,  name: "James Whitfield",         role: "Associate Attorney",            email: "james.whitfield@mitchellpi.com",          initials: "JW",  phone: "(555) 400-1005", cell: "(555) 401-1005", ext: "105", avatar: "#9B4CC9" },
  { id: 6,  name: "Sarah Nakamura",          role: "Associate Attorney",            email: "sarah.nakamura@mitchellpi.com",           initials: "SN",  phone: "(555) 400-1006", cell: "(555) 401-1006", ext: "106", avatar: "#4CC9C9" },
  { id: 7,  name: "Kevin O'Brien",           role: "Associate Attorney",            email: "kevin.obrien@mitchellpi.com",             initials: "KO",  phone: "(555) 400-1007", cell: "(555) 401-1007", ext: "107", avatar: "#C97B4C" },
  { id: 8,  name: "Angela Torres",           role: "Associate Attorney",            email: "angela.torres@mitchellpi.com",            initials: "AT",  phone: "(555) 400-1008", cell: "(555) 401-1008", ext: "108", avatar: "#4C9BC9" },
  { id: 9,  name: "William Harper",          role: "Of Counsel",                    email: "william.harper@mitchellpi.com",           initials: "WH",  phone: "(555) 400-1009", cell: "(555) 401-1009", ext: "109", avatar: "#7BC94C" },
  { id: 10, name: "Lisa Patel",              role: "Paralegal",                     email: "lisa.patel@mitchellpi.com",                initials: "LP",  phone: "(555) 400-1010", cell: "", ext: "110", avatar: "#C94C8C" },
  { id: 11, name: "Jennifer Martinez",       role: "Paralegal",                     email: "jennifer.martinez@mitchellpi.com",        initials: "JM",  phone: "(555) 400-1011", cell: "", ext: "111", avatar: "#884CC9" },
  { id: 12, name: "Thomas Bradley",          role: "Paralegal",                     email: "thomas.bradley@mitchellpi.com",           initials: "TB",  phone: "(555) 400-1012", cell: "", ext: "112", avatar: "#4CC96A" },
  { id: 13, name: "Rachel Kim",              role: "Legal Assistant",               email: "rachel.kim@mitchellpi.com",               initials: "RK",  phone: "(555) 400-1013", cell: "", ext: "113", avatar: "#C9C94C" },
  { id: 14, name: "Nicole Edwards",          role: "Legal Assistant",               email: "nicole.edwards@mitchellpi.com",           initials: "NE",  phone: "(555) 400-1014", cell: "", ext: "114", avatar: "#4C6AC9" },
  { id: 15, name: "Amanda Foster",           role: "Case Manager",                  email: "amanda.foster@mitchellpi.com",            initials: "AF",  phone: "(555) 400-1015", cell: "", ext: "115", avatar: "#C94C6A" },
  { id: 16, name: "Daniel Washington",       role: "Case Manager",                  email: "daniel.washington@mitchellpi.com",        initials: "DW",  phone: "(555) 400-1016", cell: "", ext: "116", avatar: "#4CAEC9" },
  { id: 17, name: "Stephanie Reeves",        role: "Medical Records Coordinator",   email: "stephanie.reeves@mitchellpi.com",         initials: "SR",  phone: "(555) 400-1017", cell: "", ext: "117", avatar: "#6AC94C" },
  { id: 18, name: "Michelle Tran",           role: "Intake Specialist",             email: "michelle.tran@mitchellpi.com",            initials: "MT",  phone: "(555) 400-1018", cell: "", ext: "118", avatar: "#C9844C" },
  { id: 19, name: "Karen Phillips",          role: "Office Administrator",          email: "karen.phillips@mitchellpi.com",           initials: "KP",  phone: "(555) 400-1019", cell: "", ext: "119", avatar: "#4CC9A8" },
  { id: 20, name: "Ryan Zhao",               role: "IT Specialist",                 email: "ryan.zhao@mitchellpi.com",                initials: "RZ",  phone: "(555) 400-1020", cell: "", ext: "120", avatar: "#5884C9" },
  { id: 21, name: "Marcus Coleman",          role: "Investigator",                  email: "marcus.coleman@mitchellpi.com",           initials: "MC",  phone: "(555) 400-1021", cell: "(555) 401-1021", ext: "121", avatar: "#C9A84C" },
  { id: 22, name: "Laura Jensen",            role: "Investigator",                  email: "laura.jensen@mitchellpi.com",             initials: "LJ",  phone: "(555) 400-1022", cell: "(555) 401-1022", ext: "122", avatar: "#4C7AC9" },
  { id: 23, name: "Admin",                   role: "App Admin",                     email: "admin@mitchellpi.com",                    initials: "AD",  phone: "",               cell: "", ext: "", avatar: "#C9A84C" },
];

export const CASES = [];
