module.exports = {
  testEnvironment: "node",
  testMatch: ["**/tests/**/*.test.js"],
  testTimeout: 30000,
  setupFiles: ["./tests/jest.setup.js"],
  globalTeardown: "./tests/globalTeardown.js",
  collectCoverageFrom: [
    "routes/auth.js",
    "routes/cases.js",
    "routes/permissions.js",
    "routes/inbound-email.js",
    "routes/portal-auth.js",
    "routes/external.js",
    "routes/task-flows.js",
    "middleware/auth.js",
    "middleware/clientAuth.js",
    "middleware/external-auth.js",
    "middleware/validate.js",
    "utils/encryption.js",
    "utils/session-invalidation.js",
  ],
};
